/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import conceptos.Cliente;
import conceptos.Menu;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Jiro
 */
public class interfaz extends javax.swing.JFrame {

    public String respuesta;
    public String p = "";
    public boolean fin = false;
    static Socket s;
    static DataInputStream entra;
    static DataOutputStream sale;
    Menu m = new Menu();
    /**
     * Creates new form p
     */
    public interfaz() {

        initComponents();
        area.setText("");
        area.append("Mesero: ¡Bienvenido! Ingrese el numero de su pedido\n");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        textoCliente = new javax.swing.JTextField();
        sendBttn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        finBttn = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        area.setEditable(false);
        area.setColumns(20);
        area.setRows(5);
        jScrollPane2.setViewportView(area);

        sendBttn.setBackground(new java.awt.Color(255, 255, 204));
        sendBttn.setText("Enviar mensaje");
        sendBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBttnActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/menu (1).jpg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel3.setText("RESTAURANTE");

        jLabel4.setFont(new java.awt.Font("Vladimir Script", 0, 36)); // NOI18N
        jLabel4.setText(" Las delicias");

        finBttn.setBackground(new java.awt.Color(255, 204, 204));
        finBttn.setText("Finalizar orden");
        finBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(sendBttn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(finBttn))
                    .addComponent(textoCliente)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                .addGap(490, 490, 490)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(textoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendBttn)
                    .addComponent(finBttn))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBttnActionPerformed

        // TODO add your handling code here:
        if (this.textoCliente.getText().length()>0){
        String plato="";
        respuesta = textoCliente.getText();
        if (respuesta.matches("\\d+") && respuesta.length() > 0 && Integer.parseInt(respuesta.trim()) > 0 && Integer.parseInt(respuesta.trim()) < 22) {
            area.append("Cliente: " + respuesta + "\n");
            p += respuesta.trim();
            plato=respuesta.trim();
            //System.out.println("contenido de pedido:" + p);
            area.append("Mesero: Usted ha ordenado: " +  plato(plato) + "\n");
            p += ",";
            textoCliente.setText("");

        }//*/
        }

    }//GEN-LAST:event_sendBttnActionPerformed

    private void finBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finBttnActionPerformed
        // TODO add your handling code here:
        
        if (p.length()!=0){
        int index, total;

        m = new Menu();
        String[] ej2 = p.split(",");
        int[] id = new int[ej2.length];
        String[] nombre = new String[ej2.length];
        int[] precio = new int[ej2.length];
        for (int i = 0; i < ej2.length; i++) {
            id[i] = Integer.parseInt(ej2[i]);
        }
        total = 0;
        index = 0;
        for (int i = 0; i < ej2.length; i++) {
            index = m.getIndex(id[i]);
            total += m.getCosto(index);//se obtiene el total del pedido para poder imprimir
            nombre[i] = m.getNombre(index);//se obtiene un arreglo de todos los nombres de los platillos para imprimir
            precio[i] = m.getCosto(index);//se obtiene un arreglo de todos los precios para poder imprimir
        }
        area.append("Mesero: Su orden es: \n");
        for (int i = 0; i < ej2.length; i++) {
            area.append("- "+nombre[i]+"\n");// + " -> $" + precio[i]+"\n");
        }
        
        area.append("Mesero: Orden en proceso\n");
        fin = true;
        }
        
    }//GEN-LAST:event_finBttnActionPerformed

    public String getRespuesta() {
        return respuesta;
    }

    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }

    public void settext(String mensaje) {
        area.append("Mesero: " + mensaje);
    }

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);

            }
        });
    }//*/
private String plato(String p){
    return m.getNombre(m.getIndex(Integer.parseInt(p)));
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea area;
    public javax.swing.JButton finBttn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    public javax.swing.JButton sendBttn;
    public javax.swing.JTextField textoCliente;
    // End of variables declaration//GEN-END:variables
}
